name: my_star_schema_project
version: '1.0'
config-version: 2

profile: my_star_schema_profile

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  my_star_schema_project:
    +materialized: view
