[tool.poetry]
name = "duckdb-dbt"
version = "0.1.0"
description = ""
authors = ["tkc"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
dbt-core = "^1.9.2"
dbt-duckdb = "^1.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
